FROM liquibase/liquibase:4.25

WORKDIR /app

COPY . /app

CMD ["sh", "-c", "liquibase --url=$LIQUIBASE_COMMAND_URL --username=$LIQUIBASE_COMMAND_USERNAME --password=$LIQUIBASE_COMMAND_PASSWORD --changeLogFile=db/changelog/master.xml update"]
