FROM liquibase/liquibase:4.25

WORKDIR /liquibase

# copy migrations
COPY db /liquibase/db

# copy script (NO chmod step)
COPY start-liquibase.sh /start-liquibase.sh

# IMPORTANT: override entrypoint safely
ENTRYPOINT ["/bin/sh", "/start-liquibase.sh"]
