FROM liquibase/liquibase:4.25

USER root

RUN apt-get update && apt-get install -y postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /liquibase

COPY db /liquibase/db
COPY start-liquibase.sh /start-liquibase.sh

ENTRYPOINT ["/bin/sh", "/start-liquibase.sh"]
